version: '3'
services:
  datanode1:
    image: uhopper/hadoop-datanode
    hostname: datanode1.weave.local
    container_name: datanode1
    network_mode: weave
    domainname: weave
    volumes:
      - /docker_volume/datanode1:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode.weave.local:8020
